# Generated by Django 5.0.1 on 2024-02-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
