# Generated by Django 5.0.1 on 2024-02-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='name',
        ),
    ]
