# Generated by Django 5.0.1 on 2024-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_cart_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
